MetricsTestKit: expose all metrics publicly. This allows users to run checks on counters when they might not know the exact label
apple/swift-metrics pull request #127
Opened 2023-05-16 15:57 UTC by hamzahrmalik

Provide functions on TestMetrics to retrieve all counters/timers/recorders

### Motivation:

Users may want to iterate over metrics to perform some complex assertions. For example, they might want to confirm that no metrics have been emitted with a certain dimension

### Modifications:

Added functions for allRecorders, allTimers and allCounters which return arrays of TestRecorder, TestTimer and TestCounter

2023-05-16 18:36 UTC, ktoso commented
@swift-server-bot add to allowlist

2023-05-16 18:37 UTC, ktoso approved these changes
In general I think this is fine, as a testing facility.

Thanks for the PR!

2023-05-18 02:34 UTC, tomerd approved these changes

2023-05-18 02:35 UTC, tomerd approved these changes
are there any tests we need to add?

2023-05-25 14:32 UTC, FranzBusch requested changes
Shouldn't we have a `allGauges` and now also an `allMeters` method?

2023-05-25 14:32 UTC, FranzBusch commented on Sources/MetricsTestKit/TestMetrics.swift
> +    func allCounters() throws -> [TestCounter] {
This is not `public`

2023-05-26 08:58 UTC, hamzahrmalik commented
> This has a merge conflict now due to the introduced meters on main, could you rebase @hamzahrmalik ?
> 
> Otherwise LGTM so let's merge this and the follow up which adds tests to this 👍

I actually think we should merge #128 first
That one is simply a refactor, and will make this one very simple (just adding public modifiers)

2023-05-26 11:25 UTC, ktoso commented
Yeah that works, merged #128 👍

2023-05-26 12:02 UTC, merged